### ISSUE TITLE
AT Command Mode

### ISSUE THREAD

**Issue by PatchBOTS** [pictux/Bluetooth-Module-Adaptor#1]
Thanks for making this available. 
I was wondering if you could explain the procedure for getting this module into AT Command mode via the jumper. Thanks!

**Comment by pictux** [comment]
Hi PatchBOTS, sorry for the delay :( It depends on the module, you can find an explanation here: https://docs.google.com/document/u/1/d/1ynjkVsWsyqrHXVC-W6Bi92dtvlqPe6iucaHuGRRE-Cg/pub
(google translate is your friend :D). Bye!

**Comment by PatchBOTS** [comment]
No worries man.  I figured out everything I needed.  I just want to say a huge 'thank you!' your module opened up a lot of doors for me and my project.     Thanks!
